### PR TITLE
Add support for Sprockets 4.0.0

### PR DESCRIPTION
**Pull request by kou**
- [ ] I have added or updated the specs/tests.
- [x] I have verified that the specs/tests pass on my computer.
- [x] I have not attempted to bump, or alter versions.
- [ ] This is a documentation change.
- [x] This is a source change.

## Description

Sprockets 4.0.0 has been released with additional logger argument. See #589 for details.

### CODE REVIEW

**Comment by kou** [comment]
libvips on Ubuntu 16.04 (8.2.2-1) is old to use `thumbnail_image`:

https://travis-ci.org/envygeeks/jekyll-assets/jobs/595895820#L687-L688

```text
Vips::Error:
  VipsOperation: class "thumbnail_image" not found
```

So Travis CI is failing.

**Comment by dramalho** [comment]
seems like a simple enough fix, a signature change. Apart from the specs which - I'm going to say - breaks on master as well? - what's holding this up? And how can we help?

**Comment by muffinresearch** [comment]
@kou I was going to suggest trying bionic, but it doesn't look like [libvips-dev](https://packages.ubuntu.com/bionic/libvips-dev) there is new enough either. 

An alternative might be use the approach taken by ruby-vips itself, which builds and caches libvips-dev. See https://github.com/libvips/ruby-vips/issues/100 for more context.

**Comment by kou** [comment]
CI is green by building libvips instead of using `libvips-dev`.

**Comment by dramalho** [comment]
@envygeeks thoughts on this?

**Comment by envygeeks** [comment]
I've done this in a slightly different way! Thanks 💖

**Pull request closed without merging**
