### PR TITLE
Fixing clash with multilingual plugin. Use 'baseurl_root' if posible for assets path.

### PR DESCRIPTION
**Pull request by maesitos**
- [ ] I have added or updated the specs/tests.
- [x] I have verified that the specs/tests pass on my computer.
- [x] I have not attempted to bump, or alter versions.
- [ ] This is a documentation change.
- [x] This is a source change.

## Description

  What issue are you trying to resolve?
  use 'baseurl_root' if posible for assets path.
This fixes the issue with the plugin "jekyll-multiple-languages-plugin" opened here: https://github.com/envygeeks/jekyll-assets/issues/507

This pull request has also been submitted into to the master branch https://github.com/envygeeks/jekyll-assets/pull/602

### CODE REVIEW

**Comment by envygeeks** [comment]
Is `baseurl_root` a default Jekyll configuration?

**Comment by maesitos** [comment]
> Is `baseurl_root` a default Jekyll configuration?

No. It's the 'alias' the plugin [jekyll-multiple-languages-plugin](https://github.com/Anthony-Gaudino/jekyll-multiple-languages-plugin) uses before they overwrite `base_url`: 
[jekyll-multiple-languages-plugin.rb Line 110](https://github.com/Anthony-Gaudino/jekyll-multiple-languages-plugin/blob/300d00b0d5cb3c056305272f32a3d53a4a39a08c/lib/jekyll-multiple-languages-plugin.rb#L110)

I know this pull request is very coupled with another plugin but it's harmless and it might be a good practice going forward for Jekyll plugins.

**Comment by envygeeks** [comment]
Harmless is subjective. If I didn't know it was an "alias" now, I won't know in 10 months, I don't use that plugin.  Add a note inside of the source indicating why it's there, and I'll mull it over  this weekend, though at this point I still Stan not having to maintain hacks for other people's software.

**Comment by maesitos** [comment]
> Harmless is subjective. If I didn't know it was an "alias" now, I won't know in 10 months, I don't use that plugin. Add a note inside of the source indicating why it's there, and I'll mull it over this weekend, though at this point I still Stan not having to maintain hacks for other people's software.

I know it's not the most elegant solution and the comment is a bit of a smelly code specially noticeable in your such a well structured code. But maybe it's tolerable.

**Pull request merged**
